[package]
name = "plonk-ir"
version = "0.0.1"
authors = [""]
readme = "README.md"
repository = "https://github.com/heliax/plonk"
keywords = ["cryptography", "plonk", "zk-snarks", "zero-knowledge", "crypto"]
categories = ["algorithms", "cryptography", "science"]
description = "A pure-Rust implementation of the PLONK ZK-Proof algorithm."
license = "MIT OR Apache-2.0"
edition = "2021"

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --open
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[features]
# Enable Standard Library
std = []

[dependencies]
ark-ff = "0.3"
ark-ec = "0.3"
ark-bls12-377 = "0.3"
ark-bls12-381 = "0.3"
ark-ed-on-bls12-377 = "0.3"
ark-ed-on-bls12-381 = "0.3"
ark-poly = "0.3"
ark-poly-commit = "0.3"
rand="0.8.0"
plonk-core = { path = "../plonk-core", features = [ "std", "trace", "trace-print" ] }
pest = "2.1.0"
pest_derive = "2.1.0"
pest-ast = "0.3.3"
from-pest = "0.3.1"
